"""
RAG Pipeline for legal document Q&A and summarization
"""
import os
from typing import List, Optional
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_google_genai import GoogleGenerativeAI, GoogleGenerativeAIEmbeddings
from langchain.vectorstores import FAISS
from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate


class RAGPipeline:
    """
    Retrieval-Augmented Generation pipeline for legal document Q&A
    """
    
    def __init__(self, chunk_size: int = 1000, 
                 chunk_overlap: int = 200, retrieval_k: int = 3):
        """
        Initialize the RAG (Retrieval-Augmented Generation) pipeline for legal document processing.
        
        This method sets up all necessary components for document analysis including:
        - API key validation and environment setup
        - Text chunking configuration
        - Embedding model initialization
        - Language model setup for Q&A and summarization
        
        Args:
            chunk_size: Size of text chunks for document splitting (default: 1000 characters)
            chunk_overlap: Overlap between consecutive chunks to maintain context (default: 200 characters)
            retrieval_k: Number of most relevant chunks to retrieve for context (default: 3)
            
        Raises:
            ValueError: If GOOGLE_API_KEY is not found in environment variables
        """
        # Step 1: Secure API key management
        # Load Google Gemini API key from environment variables (.env file)
        # This ensures the key is never hardcoded and remains secure
        self.api_key = os.getenv("GOOGLE_API_KEY")
        if not self.api_key:
            raise ValueError("GOOGLE_API_KEY not found in environment variables. Please set it in your .env file.")
        
        # Set the API key in environment for Google SDK to use
        os.environ["GOOGLE_API_KEY"] = self.api_key
        
        # Step 2: Configure text processing parameters
        # These control how documents are split into manageable chunks
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap
        self.retrieval_k = retrieval_k
        
        # Step 3: Initialize core LangChain components
        # Text splitter: Breaks documents into overlapping chunks for better context preservation
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap
        )
        
        # Embeddings: Convert text chunks to vector representations for semantic search
        self.embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-004")
        
        # Language model: Google's Gemini for generating answers and summaries
        self.llm = GoogleGenerativeAI(model="gemini-3-flash-preview", temperature=0.7)
        
        # Step 4: Initialize vector store and retriever (created when document is processed)
        self.vector_store = None  # FAISS vector database for embeddings
        self.retriever = None     # Semantic search retriever
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap
        )
        
        self.embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-004")
        self.llm = GoogleGenerativeAI(model="gemini-3-flash-preview", temperature=0.7)
        
        self.vector_store = None
        self.retriever = None
    
    def process_document(self, text: str) -> None:
        """
        Process document: split into chunks and create embeddings.
        
        Args:
            text: Document text
        """
        # Split text into chunks
        chunks = self.text_splitter.split_text(text)
        
        # Create embeddings and vector store
        self.vector_store = FAISS.from_texts(chunks, self.embeddings)
        self.retriever = self.vector_store.as_retriever(search_kwargs={"k": self.retrieval_k})
    
    def answer_question(self, question: str) -> str:
        """
        Answer a question about the document.
        
        Args:
            question: User's question
            
        Returns:
            Answer generated by the model
        """
        if not self.retriever:
            raise ValueError("Document not processed. Please upload a document first.")
        
        # Retrieve relevant chunks
        relevant_docs = self.retriever.get_relevant_documents(question)
        
        # Create prompt template for legal Q&A
        prompt_template = """
        You are an expert legal assistant reviewing legal documents. 
        Use the following pieces of context to answer the question. 
        Be specific and cite relevant sections when applicable.
        
        Context:
        {context}
        
        Question: {question}
        
        Answer:
        """
        
        prompt = PromptTemplate(
            template=prompt_template,
            input_variables=["context", "question"]
        )
        
        # Prepare context from retrieved documents
        context = "\n".join([doc.page_content for doc in relevant_docs])
        
        # Generate answer using a modern RetrievalQA chain
        chain = RetrievalQA.from_chain_type(
            llm=self.llm,
            chain_type="stuff",
            retriever=self.retriever,
            chain_type_kwargs={"prompt": prompt}
        )
        response = chain.run(question)

        return response
    
    def summarize_document(self) -> str:
        """
        Generate a summary of the document.
        
        Returns:
            Document summary
        """
        if not self.retriever:
            raise ValueError("Document not processed. Please upload a document first.")
        
        # Get relevant chunks for summary
        summary_question = "What are the main points, key terms, and important clauses in this document?"
        relevant_docs = self.retriever.get_relevant_documents(summary_question)
        
        # Create summarization prompt
        summary_prompt = """
        You are an expert legal assistant. Based on the following sections of a legal document,
        provide a concise summary (2-3 paragraphs) that captures the main points, key obligations,
        important clauses, and critical terms.
        
        Document Sections:
        {context}
        
        Summary:
        """
        
        prompt = PromptTemplate(
            template=summary_prompt,
            input_variables=["context"]
        )
        
        # Prepare context
        context = "\n".join([doc.page_content for doc in relevant_docs])
        
        # Generate summary using the retriever and custom prompt
        chain = RetrievalQA.from_chain_type(
            llm=self.llm,
            chain_type="stuff",
            retriever=self.retriever,
            chain_type_kwargs={"prompt": prompt}
        )
        summary = chain.run(summary_question)

        return summary
    

    def extract_key_clauses(self, clause_type: str = "payment") -> List[str]:
        """
        Extract specific types of clauses from the document.
        
        Args:
            clause_type: Type of clause to extract (e.g., "termination", "payment", "confidentiality")
            
        Returns:
            List of relevant clauses
        """
        if not self.retriever:
            raise ValueError("Document not processed. Please upload a document first.")
        
        query = f"What are the {clause_type} clauses in this document?"
        relevant_docs = self.retriever.get_relevant_documents(query)
        
        return [doc.page_content for doc in relevant_docs]
